(function(root){
'use strict';
const {E,U,labs}=root.AI;
const layout=(el,controls,visual)=>{el.innerHTML=`<div class="lab-layout"><div class="lab-controls">${controls}</div><div class="lab-visual">${visual}</div></div>`;};
const activations=[['tanh','tanh'],['relu','ReLU'],['sigmoid','Sigmoid'],['linear','线性']];
const sync=(el,id,value)=>{const input=U.$('#'+id,el);if(input.type==='range'){input.min=Math.min(Number(input.min),value);input.max=Math.max(Number(input.max),value);}input.value=value;const out=U.$('#'+id+'-out',el);if(out)out.textContent=U.fmt(value,3);};
labs.map=el=>{
 let task='supervised';
 const tasks={rules:['人为规则筛选邮件','人工智能','规则来自人工编写；运行时执行条件判断，无需数据拟合。','规则系统不属于这里讨论的机器学习。'],supervised:['从已标注邮件学习分类','机器学习','输入：邮件特征。目标：正常或垃圾标签。学习信号来自标注。','既可使用线性模型，也可使用神经网络。'],self:['根据前文预测下一词元','深度学习','输入：前文词元。目标：真实的下一词元。训练目标从文本本身构造。','这里假设使用 Transformer；任务本身也可用其他模型实现。'],reinforce:['根据奖励学习走迷宫','机器学习','输入：环境状态。行动：移动方向。奖励：抵达终点、碰壁等反馈。','强化学习也可以用表格或非神经网络函数；并非天然属于深度学习。']};
 layout(el,U.select('map-task','选一个具体实现',Object.entries(tasks).map(([k,v])=>[k,v[0]]),task)+'<p class="control-note">外框表示研究范围，内框表示常见方法子集。任务与学习范式是额外的分类轴。</p>','<div id="scope-map"></div><div id="task-info" class="task-info"></div>');
 function draw(){const t=tasks[task];U.$('#scope-map',el).innerHTML=`<div class="scope-box ${t[1]==='人工智能'?'active-scope':''}"><div class="scope-title">人工智能 <span>完成感知、推理与决策等任务</span></div><div class="scope-box ${t[1]==='机器学习'?'active-scope':''}"><div class="scope-title">机器学习 <span>从数据与反馈中学习</span></div><div class="scope-box ${t[1]==='深度学习'?'active-scope':''}"><div class="scope-title">深度学习 <span>多层神经网络</span></div><p class="small muted" style="margin:12px 0 0">表示 → 组合 → 预测</p></div></div></div>`;U.$('#task-info',el).innerHTML=`<strong>${t[0]}</strong><br>${t[2]}<p class="small muted" style="margin:10px 0 0">${t[3]}</p>`;}
 U.$('#map-task',el).onchange=e=>{task=e.target.value;draw();};el.getSnapshot=()=>({task:tasks[task][0],scope:tasks[task][1]});draw();
};
labs.vectors=el=>{
 let a=[1,.5,0,1],angle=35,length=1.1;
 const matrix=a.map((v,i)=>`<label for="mat-${i}">a${Math.floor(i/2)+1}${i%2+1}<input id="mat-${i}" type="number" value="${v}" min="-2" max="2" step="0.1"></label>`).join('');
 layout(el,`<p class="figure-title">编辑 2×2 矩阵 A</p><div class="matrix-small">${matrix}</div>${U.select('matrix-preset','变换预设',[['custom','自定义'],['identity','单位矩阵'],['rotate','逆时针旋转 90°'],['shear','水平剪切'],['collapse','压到一条线']], 'custom')}${U.range('vector-angle','输入向量方向 / °',-180,180,1,angle)}${U.range('vector-length','输入向量长度',.1,2,.1,length)}`,'<p class="figure-title">观察基向量与平面网格</p><div id="matrix-plot" class="chart"></div>'+U.legend([['原始向量 x','gray'],['变换后 Ax','teal'],['变换后的网格','orange']])+'<div id="matrix-stats" class="stats"></div>');
 function draw(){const transform=([x,y])=>[a[0]*x+a[1]*y,a[2]*x+a[3]*y],x=[length*Math.cos(angle*Math.PI/180),length*Math.sin(angle*Math.PI/180)],y=transform(x),series=[];for(let t=-2;t<=2;t+=.5){series.push({points:[[-2,t],[2,t]].map(transform),color:'#d9b6a0',width:.8});series.push({points:[[t,-2],[t,2]].map(transform),color:'#d9b6a0',width:.8});}series.push({points:[[0,0],x],color:'gray',dash:true,width:3},{points:[[0,0],y],color:'teal',width:3},{points:[y],type:'scatter',color:'teal',radius:5},{points:[transform([1,0]),transform([0,1])],type:'scatter',color:'orange'});U.plot(U.$('#matrix-plot',el),series,{xmin:-3,xmax:3,ymin:-3,ymax:3,title:'矩阵变换：灰色原始向量，青色输出向量，橙色变换网格'});U.stats(U.$('#matrix-stats',el),[['输入 x',x.map(v=>U.fmt(v,2)).join(', ')],['输出 Ax',y.map(v=>U.fmt(v,2)).join(', ')],['行列式 det(A)',U.fmt(a[0]*a[3]-a[1]*a[2],2)]]);}
 a.forEach((_,i)=>U.$('#mat-'+i,el).oninput=e=>{if(e.target.value===''||!e.target.checkValidity())return;a[i]=Number(e.target.value);U.$('#matrix-preset',el).value='custom';draw();});
 U.$('#matrix-preset',el).onchange=e=>{const presets={identity:[1,0,0,1],rotate:[0,-1,1,0],shear:[1,1,0,1],collapse:[1,.5,2,1]};if(presets[e.target.value]){a=presets[e.target.value].slice();a.forEach((v,i)=>U.$('#mat-'+i,el).value=v);draw();}};
 U.bindRange(el,'vector-angle',v=>{angle=v;draw();});U.bindRange(el,'vector-length',v=>{length=v;draw();});el.getSnapshot=()=>({matrix:a,angle,length,determinant:a[0]*a[3]-a[1]*a[2]});draw();
};
labs.regression=el=>{
 const data=E.regressionData();let w=-.7,b=.9,lr=.08,iteration=0;
 layout(el,U.range('reg-w','权重 w',-2,2,.01,w)+U.range('reg-b','偏置 b',-1.5,1.5,.01,b)+U.range('reg-lr','学习率 η',.01,.3,.01,lr)+'<div class="button-row"><button id="reg-run" class="primary">自动拟合</button><button id="reg-step">走一步</button><button id="reg-reset">重置</button></div><p class="control-note">22 个固定合成样本；全批量梯度下降。竖线为残差。自动拟合最多 400 步。</p>','<div id="reg-formula" class="formula compact-formula"></div><div id="reg-plot" class="chart"></div>'+U.legend([['观测样本','gray'],['当前预测','teal'],['残差','orange']])+'<div id="reg-stats" class="stats"></div><p id="reg-status" class="lab-status" role="status"></p>');
 function draw(){const g=E.regression(data,w,b);U.$('#reg-formula',el).textContent=`ŷ = ${U.fmt(w,3)}x ${b>=0?'+':'−'} ${U.fmt(Math.abs(b),3)}`;U.plot(U.$('#reg-plot',el),[{points:data.map(p=>[p.x,p.y]),type:'scatter',color:'gray'},{points:[[-1.6,w*-1.6+b],[1.6,w*1.6+b]],color:'teal'}],{xmin:-1.7,xmax:1.7,ymin:-2,ymax:2.5,xlabel:'输入 x',ylabel:'目标 / 预测 y',title:'线性回归的真实拟合与残差',extra:(sx,sy)=>data.map(p=>`<path d="M${sx(p.x)},${sy(p.y)}V${sy(w*p.x+b)}" stroke="#b65b2980"/>`).join('')});U.stats(U.$('#reg-stats',el),[['均方误差 MSE',U.fmt(g.loss,5)],['∂L/∂w',U.fmt(g.dw,4)],['∂L/∂b',U.fmt(g.db,4)],['已更新步数',iteration]]);sync(el,'reg-w',w);sync(el,'reg-b',b);}
 function step(){const g=E.regression(data,w,b);if(iteration>=400||Math.hypot(g.dw,g.db)<1e-7){U.$('#reg-status',el).textContent=iteration>=400?'已到 400 步，可重置后继续实验。':'梯度已很小，拟合停止。';return false;}w-=lr*g.dw;b-=lr*g.db;iteration++;draw();return true;}
 const loop=new U.Loop(step,70,r=>U.$('#reg-run',el).textContent=r?'暂停拟合':'自动拟合');
 for(const [id,set]of [['reg-w',v=>w=v],['reg-b',v=>b=v],['reg-lr',v=>lr=v]])U.bindRange(el,id,v=>{loop.stop();set(v);iteration=0;U.$('#reg-status',el).textContent='参数已修改；从当前位置重新开始。';draw();});
 U.$('#reg-run',el).onclick=()=>loop.toggle();U.$('#reg-step',el).onclick=()=>{loop.stop();step();};U.$('#reg-reset',el).onclick=()=>{loop.stop();w=-.7;b=.9;iteration=0;draw();U.$('#reg-status',el).textContent='已重置权重与偏置。';};el.getSnapshot=()=>({w,b,lr,iteration,...E.regression(data,w,b)});draw();return()=>loop.dispose();
};
labs.neuron=el=>{
 const s={x1:1,x2:.5,w1:.8,w2:-.4,b:.1,activation:'sigmoid'};
 layout(el,U.select('neuron-activation','激活函数 φ',activations,s.activation)+[['x1','输入 x₁'],['x2','输入 x₂'],['w1','权重 w₁'],['w2','权重 w₂'],['b','偏置 b']].map(([k,t])=>U.range('neu-'+k,t,-2,2,.05,s[k])).join(''),'<div id="neuron-formula" class="formula compact-formula"></div><div id="neuron-plot" class="chart"></div>'+U.legend([['激活函数 φ(z)','teal'],['局部导数 φ′(z)','orange']])+'<div id="neuron-stats" class="stats"></div><p id="neuron-status" class="lab-status"></p>');
 function draw(){const z=s.w1*s.x1+s.w2*s.x2+s.b,act=E.activation(z,s.activation),der=E.derivative(z,s.activation),bound=Math.max(5,Math.ceil(Math.abs(z)+1));U.$('#neuron-formula',el).textContent=`z = (${U.fmt(s.w1,2)} × ${U.fmt(s.x1,2)}) + (${U.fmt(s.w2,2)} × ${U.fmt(s.x2,2)}) + ${U.fmt(s.b,2)}`;U.plot(U.$('#neuron-plot',el),[{points:U.curve(x=>E.activation(x,s.activation),-bound,bound),color:'teal'},{points:U.curve(x=>E.derivative(x,s.activation),-bound,bound),color:'orange',dash:true},{points:[[z,act]],type:'scatter',color:'teal',radius:6}],{xmin:-bound,xmax:bound,ymin:s.activation==='linear'?-bound:-1.3,ymax:['relu','linear'].includes(s.activation)?bound:1.3,xlabel:'加权输入 z',ylabel:'函数值 / 导数',title:'激活函数及其导数，实心点为当前输出'});U.stats(U.$('#neuron-stats',el),[['加权输入 z',U.fmt(z,3)],['神经元输出 a',U.fmt(act,4)],['局部导数',U.fmt(der,4)]]);U.$('#neuron-status',el).textContent=s.activation==='relu'&&z===0?'ReLU 在 0 处不可导，本实验取导数为 0。':Math.abs(der)<.03?'这个位置的导数很小，反向信号经过此处会受到抑制。':'移动输入，观察当前位置的斜率如何改变。';}
 Object.keys(s).filter(k=>k!=='activation').forEach(k=>U.bindRange(el,'neu-'+k,v=>{s[k]=v;draw();}));U.$('#neuron-activation',el).onchange=e=>{s.activation=e.target.value;draw();};el.getSnapshot=()=>({...s});draw();
};
labs.loss=el=>{
 let p=.8,y=1,logits=[1.4,.2,-.6],target=0;
 layout(el,U.range('loss-p','预测为 1 的概率 p',.001,.999,.001,p)+U.select('loss-y','真实标签 y',[[1,'1 / 正类'],[0,'0 / 负类']],y)+'<p class="control-note">二分类曲线使用自然对数。p 在 0.001–0.999 之间，避免直接计算 ln(0)。训练引擎则直接使用稳定的 logits 公式。</p>','<p class="figure-title">同一概率，标签不同，代价不同</p><div id="loss-plot" class="chart"></div>'+U.legend([['真实标签 y=1','teal'],['真实标签 y=0','orange']])+'<div id="loss-stats" class="stats"></div>');
 el.insertAdjacentHTML('beforeend','<div class="report-note"><strong>多分类实验</strong>　三个候选共同组成一个概率分布。调大一项，其他项的概率也会变化。</div><div class="lab-layout"><div class="lab-controls">'+logits.map((v,i)=>U.range('logit-'+i,'类别 '+['A','B','C'][i]+' 的 logit',-5,5,.1,v)).join('')+U.select('ce-target','真实类别',[[0,'A'],[1,'B'],[2,'C']],target)+'</div><div class="lab-visual"><div id="softmax-bars" class="bars"></div><div id="ce-stats" class="stats"></div><div class="formula compact-formula">pⱼ = exp(zⱼ) / Σₖ exp(zₖ)</div></div></div>');
 function draw(){const z=Math.log(p/(1-p));U.plot(U.$('#loss-plot',el),[{points:U.curve(x=>E.bce(x,1),.001,.999),color:'teal'},{points:U.curve(x=>E.bce(x,0),.001,.999),color:'orange'},{points:[[p,E.bce(p,y)]],type:'scatter',color:y?'teal':'orange',radius:6}],{xmin:0,xmax:1,ymin:0,ymax:7,xlabel:'预测概率 p',ylabel:'二元交叉熵',title:`真实标签 ${y}，概率 ${p}，损失 ${U.fmt(E.bce(p,y),4)}`});U.stats(U.$('#loss-stats',el),[['二元交叉熵',U.fmt(E.bceLogit(z,y),5)],['对应 logit z',U.fmt(z,4)],['∂L/∂z = p−y',U.fmt(p-y,4)]]);const probs=E.softmax(logits);U.bars(U.$('#softmax-bars',el),['类别 A','类别 B','类别 C'],probs,target);U.stats(U.$('#ce-stats',el),[['真实类概率',U.pct(probs[target])],['多类交叉熵',U.fmt(E.crossEntropy(logits,target),5)],['概率总和',U.fmt(probs.reduce((s,v)=>s+v,0),4)]]);}
 U.bindRange(el,'loss-p',v=>{p=v;draw();});U.$('#loss-y',el).onchange=e=>{y=Number(e.target.value);draw();};logits.forEach((_,i)=>U.bindRange(el,'logit-'+i,v=>{logits[i]=v;draw();}));U.$('#ce-target',el).onchange=e=>{target=Number(e.target.value);draw();};el.getSnapshot=()=>({p,y,bce:E.bce(p,y),logits:logits.slice(),target,ce:E.crossEntropy(logits,target)});draw();
};
labs.descent=el=>{
 let start=[2.4,1.2],eta=.08,beta=.6,pos=start.slice(),plain=start.slice(),velocity=[0,0],trace=[pos.slice()],baseline=[plain.slice()],steps=0,halted=false;
 const loss=x=>.5*(x[0]**2+8*x[1]**2);
 layout(el,U.range('gd-eta','学习率 η',.005,.35,.005,eta)+U.range('gd-beta','动量 β',0,.95,.05,beta)+U.range('gd-u','起点参数 u',-2.8,2.8,.1,start[0])+U.range('gd-v','起点参数 v',-2.8,2.8,.1,start[1])+'<div class="button-row"><button id="gd-run" class="primary">开始下降</button><button id="gd-step">走一步</button><button id="gd-reset">重置轨迹</button></div><p class="control-note">修改任何配置会重置两条轨迹。坐标是参数，不是训练样本。离开页面会暂停。</p>','<div class="formula compact-formula">L(u,v) = ½(u² + 8v²)</div><div id="gd-plot" class="chart"></div>'+U.legend([['带动量的轨迹','teal'],['普通梯度，同一 η','orange']])+'<div id="gd-stats" class="stats"></div><p id="gd-status" class="lab-status" role="status"></p>');
 function draw(){U.plot(U.$('#gd-plot',el),[{points:baseline,color:'orange',dash:true},{points:trace,color:'teal'},{points:[pos],type:'scatter',color:'teal',radius:5}],{xmin:-3,xmax:3,ymin:-3,ymax:3,xlabel:'参数 u',ylabel:'参数 v',title:'二次损失等高线和真实梯度下降轨迹',extra:(sx,sy)=>[.1,.5,1,2,4,8,16,32].map(l=>`<ellipse cx="${sx(0)}" cy="${sy(0)}" rx="${Math.abs(sx(Math.sqrt(2*l))-sx(0))}" ry="${Math.abs(sy(Math.sqrt(2*l/8))-sy(0))}" fill="none" stroke="#607e8735" stroke-width="1"/>`).join('')});U.stats(U.$('#gd-stats',el),[['动量轨迹损失',U.fmt(loss(pos),5)],['普通梯度损失',U.fmt(loss(plain),5)],['更新步数',steps],['当前参数 u, v',pos.map(v=>U.fmt(v,3)).join(', ')]]);}
 function step(){if(halted)return false;velocity=[beta*velocity[0]+pos[0],beta*velocity[1]+8*pos[1]];pos=pos.map((v,i)=>v-eta*velocity[i]);plain=[plain[0]*(1-eta),plain[1]*(1-8*eta)];steps++;trace.push(pos.slice());baseline.push(plain.slice());draw();if(Math.max(...pos.map(Math.abs),...plain.map(Math.abs))>6){halted=true;U.$('#gd-status',el).textContent='轨迹超出视窗，已停止。较大的步长造成过冲；请降低学习率。';return false;}if(steps>=200||(loss(pos)<1e-10&&loss(plain)<1e-10)){halted=true;U.$('#gd-status',el).textContent=steps>=200?'已完成 200 步，请重置后继续比较。':'两条轨迹已非常接近谷底。';return false;}U.$('#gd-status',el).textContent='动量可能造成短暂过冲，观察损失而不只看位置。';return true;}
 const loop=new U.Loop(step,180,r=>U.$('#gd-run',el).textContent=r?'暂停':'开始下降');
 function reset(){loop.stop();pos=start.slice();plain=start.slice();velocity=[0,0];trace=[pos.slice()];baseline=[plain.slice()];steps=0;halted=false;U.$('#gd-status',el).textContent='两条轨迹从同一个起点出发。';draw();}
 for(const [id,set]of [['gd-eta',v=>eta=v],['gd-beta',v=>beta=v],['gd-u',v=>start[0]=v],['gd-v',v=>start[1]=v]])U.bindRange(el,id,v=>{set(v);reset();});U.$('#gd-run',el).onclick=()=>loop.toggle();U.$('#gd-step',el).onclick=()=>{loop.stop();step();};U.$('#gd-reset',el).onclick=reset;el.getSnapshot=()=>({eta,beta,steps,start:start.slice(),position:pos.slice(),loss:loss(pos),plainLoss:loss(plain)});reset();return()=>loop.dispose();
};
labs.backprop=el=>{
 let x=1.5,w=.8,b=-.3,y=1,stage=0;
 layout(el,U.range('bp-x','输入 x',-2,2,.05,x)+U.range('bp-w','权重 w',-4,4,.05,w)+U.range('bp-b','偏置 b',-4,4,.05,b)+U.select('bp-y','真实标签',[[1,'1'],[0,'0']],y)+'<div class="button-row"><button id="bp-next" class="primary">下一步</button><button id="bp-update" disabled>更新参数</button></div><p class="control-note">更新使用 η=0.1；完成第 4 步后可应用梯度。修改参数会重新从前向计算开始。</p>','<div id="bp-stages" class="step-track"></div><div id="bp-flow" class="flow-graph"></div><div id="bp-explain" class="step-explain" role="status"></div><div id="bp-check" class="stats"></div>');
 const names=['加权求和','计算概率','计算损失','反向求导'];
 function draw(){const f=E.singleNeuron(x,w,b,y),numeric=E.finiteDifference(v=>E.singleNeuron(x,v,b,y).loss,w),texts=[`<strong>1. 加权求和</strong><br>z = wx+b = ${U.fmt(w,3)}×${U.fmt(x,3)} + (${U.fmt(b,3)}) = ${U.fmt(f.z,4)}。记录 x 与 z，后面求导还会用到。`,`<strong>2. 计算预测概率</strong><br>p = σ(z) = ${U.fmt(f.p,6)}。此处 Sigmoid 的局部导数 p(1−p) = ${U.fmt(f.p*(1-f.p),6)}。`,`<strong>3. 计算损失</strong><br>标签 y=${y}，BCE=${U.fmt(f.loss,6)}。模型给真实类别的概率是 ${U.fmt(y?f.p:1-f.p,6)}。到这里还没有更新任何参数。`,`<strong>4. 反向求导</strong><br>∂L/∂z=p−y=${U.fmt(f.dz,6)}。<br>∂L/∂w=(p−y)x=${U.fmt(f.dw,6)}；∂L/∂b=p−y=${U.fmt(f.db,6)}。<br>下面以 h=10⁻⁵ 独立计算中心差分，核对权重梯度。`];U.$('#bp-stages',el).innerHTML=names.map((n,i)=>`<button data-stage="${i}" class="${stage===i?'active':''}" aria-pressed="${stage===i}">${i+1}. ${n}</button>`).join('');U.$('#bp-flow',el).innerHTML=[['z',f.z,'wx+b'],['p',f.p,'σ(z)'],['L',f.loss,'BCE(p,y)'],['∂L/∂w',f.dw,'(p−y)x']].map(([n,v,d],i)=>`<div class="flow-node ${i===stage?'active':''}"><div class="flow-label">${n}</div><div class="flow-value">${i<=stage?U.fmt(v,3):'· · ·'}</div><div class="flow-detail">${d}</div></div>`).join('');U.$('#bp-explain',el).innerHTML=texts[stage];U.$('#bp-update',el).disabled=stage!==3;U.$('#bp-next',el).textContent=stage===3?'从头查看':'下一步';U.$('#bp-check',el).hidden=stage!==3;U.stats(U.$('#bp-check',el),[['解析 ∂L/∂w',U.fmt(f.dw,7)],['中心差分',U.fmt(numeric,7)],['绝对差',Math.abs(f.dw-numeric).toExponential(2)]]);U.$$('[data-stage]',el).forEach(button=>button.onclick=()=>{stage=Number(button.dataset.stage);draw();});}
 for(const [id,set]of [['bp-x',v=>x=v],['bp-w',v=>w=v],['bp-b',v=>b=v]])U.bindRange(el,id,v=>{set(v);stage=0;draw();});U.$('#bp-y',el).onchange=e=>{y=Number(e.target.value);stage=0;draw();};U.$('#bp-next',el).onclick=()=>{stage=(stage+1)%4;draw();};U.$('#bp-update',el).onclick=()=>{const f=E.singleNeuron(x,w,b,y);w-=.1*f.dw;b-=.1*f.db;sync(el,'bp-w',w);sync(el,'bp-b',b);stage=0;draw();U.toast('已应用梯度；重新前向计算检查新损失。');};el.getSnapshot=()=>({x,w,b,y,...E.singleNeuron(x,w,b,y)});draw();
};
})(globalThis);
