/* Dedicated route overview; shared chapters keep stable IDs and saved notes. */
(function(root){
  'use strict';
  const {C,U}=root.AI;
  root.AI.renderLLMTrack=function(main){
    document.title='大语言模型研习室 · 可见 AI';
    const chapters=C.chapters.filter(c=>c.track==='llm'),done=chapters.filter(c=>U.state.completed.includes(c.id)).length;
    main.innerHTML=`<div class="breadcrumb"><a href="#/">学习总览</a><span>/ 大语言模型进阶</span></div><section class="llm-hero"><div><span class="llm-eyebrow">从深度学习基础，走进语言模型内部</span><h1>理解一个词元，<br>如何变成回答。</h1><p>先把文本和损失对齐，再拆开结构、亲手训练，最后把适配、推理与评估放回同一个系统。${chapters.length} 个进阶专题，每一章都有可操作的实验和可追溯的原始资料。</p><div class="home-actions"><a class="button-primary" href="#/learn/llm-objective">进入进阶路线</a><a class="secondary-link" href="#/learn/llm-train">先训练微型解码器 ↗</a></div><p class="small">进阶进度 ${done} / ${chapters.length} · 不需要账户、密钥、显卡或模型下载</p></div><div class="llm-hero-board"><h2>260 个参数的语言模型</h2><div class="llm-tokens"><span class="llm-token"><small>前缀</small>蓝猫</span><span class="llm-token"><small>每步重新前向</small>下一词概率</span><span class="llm-token"><small>选择并接回</small>自回归</span></div><div class="llm-model-flow"><span><b>01 · 数字表示</b>词嵌入与位置</span><span><b>02 · 读取上下文</b>因果注意力</span><span><b>03 · 特征变换</b>残差与前馈</span><span><b>04 · 学习目标</b>词表头与交叉熵</span></div><p>这张路线卡不伪装成模型输出。进入实验后，权重、梯度、损失与生成都由实际计算得到。</p></div></section><div class="llm-track-intro"><strong>把“能算”“能学”“能部署”分开看。</strong><br>精确数值实验用于验证公式；260 参数解码器和 LoRA 矩阵案例真的更新参数；资源与调度实验明确是带假设的估算。原有基础课程和离线入口完整保留。</div><div class="llm-route-grid">${C.groups.map((g,i)=>({g,i})).filter(({g})=>g.track==='llm').map(({g,i})=>`<section class="llm-route-section"><header><span class="small muted">${g.range}</span><h2>${g.title}</h2><p>${g.subtitle}</p></header>${chapters.filter(c=>c.group===i).map(c=>`<a class="course-link" href="#/learn/${c.id}"><span class="number">${c.no}</span><div><strong>${c.short}</strong><p>${c.summary}</p></div><span aria-hidden="true">${U.state.completed.includes(c.id)?'✓':'↗'}</span></a>`).join('')}</section>`).join('')}</div><section><h2>与《动手学深度学习》一起读</h2><p class="lesson-lead">本站用中文原创解释和浏览器实验搭桥；教材的完整推导、PyTorch 实现和习题从原站继续阅读。不是 D2L 官方分站，也没有复制教材正文或图片。</p><div class="llm-reading-grid">${C.llmReading.map(([title,description,url,chapter])=>`<article class="llm-reading"><h3>${title}</h3><p>${description}</p><a href="${url}" target="_blank" rel="noopener noreferrer">阅读 D2L 原章节 ↗</a><a href="#/learn/${chapter}">对应本站实验</a></article>`).join('')}</div></section><div class="llm-track-intro"><strong>怎么学这一条路线</strong><br>对每章先做“先试这件事”，改变一个变量并记录结果；再看原理与展开公式，最后完成迁移练习和自测。需要补课时，前置链接会带回原来的矩阵、反向传播或 Transformer 章节。<br><a href="#/glossary">查阅 ${C.glossary.length} 项概念词典</a> · <a href="#/journal">打开实验本</a> · <a href="#/sources">查看原始来源和许可</a></div>`;
  };
})(globalThis);
